- hosts: all
  sudo: yes
  remote_user: root
  tasks:
    - name: yum install common tools
      yum: name={{item}} state=latest
      with_items:
        - '*'
        - vim 
        - expect
        - unzip
    - copy: cp src={{item}} dest=~/
      with_items:
        - jasperreports-server-6.0.1-linux-x64-installer.run
        - jasperserver.license 
        - installjasper.sh
        - newrelic-java-3.21.0.zip
        - Export20151011.tar.gz
        - jasperCustom.tar.gz
    - file: path=~/{{item}} mode="u+rwx,g+rx,o-rwx"
      with_items:
        - jasperreports-server-6.0.1-linux-x64-installer.run
        - jasperserver.license 
        - installjasper.sh
        - newrelic-java-3.21.0.zip
        - Export20151011.tar.gz
        - jasperCustom.tar.gz
# installation
    - file: path=/opt/jasperreports-server-6.0.1 state=absent
    - name: install jasper 
      command: ~/installjasper.sh

# new relic job
    - name: copy license file to proper directory
      command: cp ~/jasperserver.license /opt/jasperreports-server-6.0.1/
    - name: unzip new relic
      command: unzip -o newrelic-java-3.21.0.zip -d /opt/jasperreports-server-6.0.1/apache-tomcat/
    - name: replace name
      command: "sed -i 's/app_name: My Application/app_name: Jasper Production/g' /opt/jasperreports-server-6.0.1/apache-tomcat/newrelic/newrelic.yml"

# import custom files
    - name: untar export
      command: tar -xzf {{item}}
      with_items:
        - Export20151011.tar.gz
        - jasperCustom.tar.gz
    - file: path=~/Export20151011 mode="u+rwx,g+rx,o-rwx"
    - name: import files
      command: ./opt/jasperreports-server-6.0.1/buildomatic/js-import.sh --input-dir ~/Export20151011

# manually move custom jars
#    - name: move files to proper location
#      command: cp -rf ~/jasper/apache-tomcat /opt/jasperreports-server-6.0.1/

# create memory manager
    - copy: cp -f src=tomcat-users.xml dest=/opt/jasperreports-server-6.0.1/apache-tomcat/conf/.

